// <auto-generated />
using System;
using AdmCC.InfraData.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdmCC.InfraData.Migrations
{
    [DbContext(typeof(AdmCCContext))]
    [Migration("20260411165844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Anuidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPagamentoPrimeiraAnuidade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaRenovacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusAnuidade")
                        .HasColumnType("int");

                    b.Property<DateTime>("VencimentoAtual")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Anuidades", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Associado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnuidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtuacaoEspecificaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailPrincipal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeAtualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PadrinhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PermitirExibirAniversario")
                        .HasColumnType("bit");

                    b.Property<int>("StatusAssociado")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneWhatsappPrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AnuidadeId")
                        .IsUnique();

                    b.HasIndex("AtuacaoEspecificaId");

                    b.HasIndex("ClusterId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("EmailPrincipal")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("EquipeAtualId");

                    b.HasIndex("EquipeOrigemId");

                    b.HasIndex("PadrinhoId");

                    b.ToTable("Associados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<Guid>("EnderecoComercialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("EnderecoComercialId");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PermitirExibicaoNaRede")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.EquipeOrigem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipeOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeOrigemId");

                    b.ToTable("EquipesOrigem", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.HistoricoAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.ToTable("HistoricosAssociado", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.AssociadoCargoLideranca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CargoLiderancaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CargoLiderancaId");

                    b.HasIndex("AssociadoId", "CargoLiderancaId", "DataInicio")
                        .IsUnique();

                    b.ToTable("AssociadosCargosLideranca", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.CargoLideranca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClassificacaoCargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CargosLideranca", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.DesignacaoLiderancaEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CargoLiderancaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.HasIndex("CargoLiderancaId");

                    b.HasIndex("EquipeId", "CargoLiderancaId", "AssociadoId", "DataInicio")
                        .IsUnique();

                    b.ToTable("DesignacoesLiderancaEquipe", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.DiretoriaEquipeVinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Indeterminado")
                        .HasColumnType("bit");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DiretoriasEquipesVinculos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.EquipeCargoAtivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CargoLiderancaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoLiderancaId");

                    b.HasIndex("EquipeId", "CargoLiderancaId")
                        .IsUnique();

                    b.ToTable("EquipesCargosAtivos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.ConexaoEstrategica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Complemento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluida")
                        .HasColumnType("bit");

                    b.Property<string>("NomeContatoOuEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StatusConexao")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneContato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoDeConexao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoDestinoId");

                    b.HasIndex("AssociadoOrigemId");

                    b.ToTable("ConexoesEstrategicas", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.NegocioRecebidoValidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoReceptorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConexaoEstrategicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPrazoEstourado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotivoNegocioNaoFechado")
                        .HasColumnType("int");

                    b.Property<bool>("PrazoEstourado")
                        .HasColumnType("bit");

                    b.Property<int>("StatusConexao")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorNegocioFechado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoReceptorId");

                    b.HasIndex("ConexaoEstrategicaId")
                        .IsUnique();

                    b.ToTable("NegociosRecebidosValidacoes", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.ParceriaAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataParceria")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoDestinoId");

                    b.HasIndex("AssociadoOrigemId", "AssociadoDestinoId")
                        .IsUnique();

                    b.ToTable("ParceriasAssociados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataEfetivaLancamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioFormacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevisaoLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaReuniaoEquipe")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HorarioReuniao")
                        .HasColumnType("time");

                    b.Property<string>("LinkReuniaoOnline")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("LocalReuniaoPresencialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModeloReuniaoDeEquipe")
                        .HasColumnType("int");

                    b.Property<string>("NomeEquipe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("NumeroComponentesAtivos")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMensalAtual")
                        .HasColumnType("int");

                    b.Property<int>("StatusEquipe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalReuniaoPresencialId");

                    b.HasIndex("NomeEquipe")
                        .IsUnique();

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataReuniao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhPresencial")
                        .HasColumnType("bit");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOcorrenciaNoMes")
                        .HasColumnType("int");

                    b.Property<bool>("Realizada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId", "DataReuniao")
                        .IsUnique();

                    b.ToTable("OcorrenciasReunioesEquipes", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.ParametroPontuacaoEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeMaximaAssociados")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMinimaAssociados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuantidadeMinimaAssociados", "QuantidadeMaximaAssociados")
                        .IsUnique()
                        .HasFilter("[QuantidadeMaximaAssociados] IS NOT NULL");

                    b.ToTable("ParametrosPontuacaoEquipe", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.PresencaReuniaoEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OcorrenciaReuniaoEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.HasIndex("OcorrenciaReuniaoEquipeId", "AssociadoId")
                        .IsUnique();

                    b.ToTable("PresencasReunioesEquipes", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.AssociadoGrupamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrupamentoEstrategicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GrupamentoEstrategicoId");

                    b.HasIndex("AssociadoId", "GrupamentoEstrategicoId")
                        .IsUnique();

                    b.ToTable("AssociadosGrupamentos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.AtuacaoEspecifica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Nome")
                        .IsUnique();

                    b.ToTable("AtuacoesEspecificas", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.GrupamentoEstrategico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("GrupamentosEstrategicos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.CicloSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEncerramento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio", "DataEncerramento")
                        .IsUnique();

                    b.ToTable("CiclosSemanais", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ParametroPontuacaoEducacional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TipoPontuacaoEducacional")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParametrosPontuacaoEducacional", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ProspectReuniaoCC", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CompartilhouApenasContato")
                        .HasColumnType("bit");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeProspect")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ValidacaoReuniaoCCId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ValidacaoReuniaoCCId");

                    b.ToTable("ProspectsReunioesCC", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.RegistroEducacional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParametroPontuacaoEducacionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TipoPontuacaoEducacional")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Validado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.HasIndex("ParametroPontuacaoEducacionalId");

                    b.ToTable("RegistrosEducacionais", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ReuniaoCC", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CicloSemanalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkReuniaoOnline")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LocalReuniao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusReuniaoCC")
                        .HasColumnType("int");

                    b.Property<int>("TipoReuniaoCC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoDestinoId");

                    b.HasIndex("AssociadoOrigemId");

                    b.HasIndex("CicloSemanalId", "AssociadoOrigemId", "AssociadoDestinoId")
                        .IsUnique();

                    b.ToTable("ReunioesCC", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ValidacaoReuniaoCC", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NaoEncontrouProspect")
                        .HasColumnType("bit");

                    b.Property<int>("PontosGerados")
                        .HasColumnType("int");

                    b.Property<Guid>("ReuniaoCCId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.HasIndex("ReuniaoCCId", "AssociadoId")
                        .IsUnique();

                    b.ToTable("ValidacoesReunioesCC", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.PerfilPublico.Entities.MidiaAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("NomeMidia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("int");

                    b.Property<Guid>("PerfilAssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilAssociadoId", "OrdemExibicao");

                    b.ToTable("MidiasAssociados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.PerfilPublico.Entities.PerfilAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescricaoProfissional")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EmailPublico")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoProfissionalUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogomarcaEmpresaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeEmpresaExibicao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PerfilPublicado")
                        .HasColumnType("bit");

                    b.Property<string>("Site")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId")
                        .IsUnique();

                    b.ToTable("PerfisAssociados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.RelatoriosAuditorias.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DadosAnterioresJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosNovosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.RelatoriosAuditorias.Entities.NotificacaoInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UsuarioDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Lida");

                    b.HasIndex("UsuarioDestinoId");

                    b.ToTable("NotificacoesInternas", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.BeneficiarioSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("SeguroAssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SeguroAssociadoId");

                    b.ToTable("BeneficiariosSeguro", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.ConsentimentoLgpdSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aceito")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeguroAssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextoConsentimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeguroAssociadoId")
                        .IsUnique();

                    b.ToTable("ConsentimentosLgpdSeguro", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.ContatoEmergencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SeguroAssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefoneSecundario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SeguroAssociadoId")
                        .IsUnique();

                    b.ToTable("ContatosEmergencia", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.SeguroAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId")
                        .IsUnique();

                    b.ToTable("SegurosAssociados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.SolicitacaoAlteracaoBeneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacaoAnalise")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacaoSolicitante")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SeguroAssociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusSolicitacaoBeneficiario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeguroAssociadoId");

                    b.ToTable("SolicitacoesAlteracaoBeneficiario", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.SubstitutoAssociado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoSubstitutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoTitularId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OcorrenciaReuniaoEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusValidacaoPresenca")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoSubstitutoId");

                    b.HasIndex("AssociadoTitularId");

                    b.HasIndex("OcorrenciaReuniaoEquipeId");

                    b.ToTable("SubstitutosAssociados", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.SubstitutoExterno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoTitularId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OcorrenciaReuniaoEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusValidacaoPresenca")
                        .HasColumnType("int");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoTitularId");

                    b.HasIndex("Cpf");

                    b.HasIndex("OcorrenciaReuniaoEquipeId");

                    b.ToTable("SubstitutosExternos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.VisitaInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OcorrenciaReuniaoEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusValidacaoPresenca")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoVisitanteId");

                    b.HasIndex("OcorrenciaReuniaoEquipeId");

                    b.ToTable("VisitasInternas", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.VisitanteExterno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociadoResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OcorrenciaReuniaoEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusValidacaoPresenca")
                        .HasColumnType("int");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoResponsavelId");

                    b.HasIndex("Cpf");

                    b.HasIndex("OcorrenciaReuniaoEquipeId");

                    b.ToTable("VisitantesExternos", (string)null);
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Associado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Anuidade", "Anuidade")
                        .WithMany()
                        .HasForeignKey("AnuidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Estrategia.Entities.AtuacaoEspecifica", "AtuacaoEspecifica")
                        .WithMany("Associados")
                        .HasForeignKey("AtuacaoEspecificaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Estrategia.Entities.Cluster", "Cluster")
                        .WithMany("Associados")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeAtualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.EquipeOrigem", "EquipeOrigem")
                        .WithMany()
                        .HasForeignKey("EquipeOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Padrinho")
                        .WithMany("Indicados")
                        .HasForeignKey("PadrinhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anuidade");

                    b.Navigation("AtuacaoEspecifica");

                    b.Navigation("Cluster");

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");

                    b.Navigation("EquipeOrigem");

                    b.Navigation("Padrinho");
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Empresa", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Endereco", "EnderecoComercial")
                        .WithMany()
                        .HasForeignKey("EnderecoComercialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnderecoComercial");
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.EquipeOrigem", b =>
                {
                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.HistoricoAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany("HistoricoStatus")
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.AssociadoCargoLideranca", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CargosLiderancas.Entities.CargoLideranca", null)
                        .WithMany("AssociadosCargos")
                        .HasForeignKey("CargoLiderancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.DesignacaoLiderancaEquipe", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CargosLiderancas.Entities.CargoLideranca", null)
                        .WithMany("Designacoes")
                        .HasForeignKey("CargoLiderancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.DiretoriaEquipeVinculo", b =>
                {
                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.EquipeCargoAtivo", b =>
                {
                    b.HasOne("AdmCC.Domain.CargosLiderancas.Entities.CargoLideranca", null)
                        .WithMany("EquipesCargosAtivos")
                        .HasForeignKey("CargoLiderancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.ConexaoEstrategica", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.NegocioRecebidoValidacao", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.ConexoesParcerias.Entities.ConexaoEstrategica", "ConexaoEstrategica")
                        .WithOne("ValidacaoRecebimento")
                        .HasForeignKey("AdmCC.Domain.ConexoesParcerias.Entities.NegocioRecebidoValidacao", "ConexaoEstrategicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConexaoEstrategica");
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.ParceriaAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.Equipe", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Endereco", "LocalReuniaoPresencial")
                        .WithMany()
                        .HasForeignKey("LocalReuniaoPresencialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalReuniaoPresencial");
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", b =>
                {
                    b.HasOne("AdmCC.Domain.Equipes.Entities.Equipe", "Equipe")
                        .WithMany("OcorrenciasReuniao")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.PresencaReuniaoEquipe", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", "OcorrenciaReuniaoEquipe")
                        .WithMany("Presencas")
                        .HasForeignKey("OcorrenciaReuniaoEquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("OcorrenciaReuniaoEquipe");
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.AssociadoGrupamento", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany("AssociadosGrupamentos")
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Estrategia.Entities.GrupamentoEstrategico", "GrupamentoEstrategico")
                        .WithMany("AssociadosGrupamentos")
                        .HasForeignKey("GrupamentoEstrategicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("GrupamentoEstrategico");
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.AtuacaoEspecifica", b =>
                {
                    b.HasOne("AdmCC.Domain.Estrategia.Entities.Cluster", "Cluster")
                        .WithMany("AtuacoesEspecificas")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ProspectReuniaoCC", b =>
                {
                    b.HasOne("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ValidacaoReuniaoCC", "ValidacaoReuniaoCC")
                        .WithMany("Prospects")
                        .HasForeignKey("ValidacaoReuniaoCCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidacaoReuniaoCC");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.RegistroEducacional", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ParametroPontuacaoEducacional", "ParametroPontuacaoEducacional")
                        .WithMany()
                        .HasForeignKey("ParametroPontuacaoEducacionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("ParametroPontuacaoEducacional");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ReuniaoCC", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoDestino")
                        .WithMany()
                        .HasForeignKey("AssociadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoOrigem")
                        .WithMany()
                        .HasForeignKey("AssociadoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.CicloSemanal", "CicloSemanal")
                        .WithMany("ReunioesCC")
                        .HasForeignKey("CicloSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociadoDestino");

                    b.Navigation("AssociadoOrigem");

                    b.Navigation("CicloSemanal");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ValidacaoReuniaoCC", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ReuniaoCC", "ReuniaoCC")
                        .WithMany("Validacoes")
                        .HasForeignKey("ReuniaoCCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("ReuniaoCC");
                });

            modelBuilder.Entity("AdmCC.Domain.PerfilPublico.Entities.MidiaAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.PerfilPublico.Entities.PerfilAssociado", "PerfilAssociado")
                        .WithMany("Midias")
                        .HasForeignKey("PerfilAssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAssociado");
                });

            modelBuilder.Entity("AdmCC.Domain.PerfilPublico.Entities.PerfilAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associado");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.BeneficiarioSeguro", b =>
                {
                    b.HasOne("AdmCC.Domain.Seguro.Entities.SeguroAssociado", "SeguroAssociado")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("SeguroAssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeguroAssociado");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.ConsentimentoLgpdSeguro", b =>
                {
                    b.HasOne("AdmCC.Domain.Seguro.Entities.SeguroAssociado", "SeguroAssociado")
                        .WithOne("ConsentimentoLgpd")
                        .HasForeignKey("AdmCC.Domain.Seguro.Entities.ConsentimentoLgpdSeguro", "SeguroAssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeguroAssociado");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.ContatoEmergencia", b =>
                {
                    b.HasOne("AdmCC.Domain.Seguro.Entities.SeguroAssociado", "SeguroAssociado")
                        .WithOne("ContatoEmergencia")
                        .HasForeignKey("AdmCC.Domain.Seguro.Entities.ContatoEmergencia", "SeguroAssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeguroAssociado");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.SeguroAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "Associado")
                        .WithMany()
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associado");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.SolicitacaoAlteracaoBeneficiario", b =>
                {
                    b.HasOne("AdmCC.Domain.Seguro.Entities.SeguroAssociado", "SeguroAssociado")
                        .WithMany("SolicitacoesAlteracaoBeneficiario")
                        .HasForeignKey("SeguroAssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeguroAssociado");
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.SubstitutoAssociado", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoSubstituto")
                        .WithMany()
                        .HasForeignKey("AssociadoSubstitutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoTitular")
                        .WithMany()
                        .HasForeignKey("AssociadoTitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", "OcorrenciaReuniaoEquipe")
                        .WithMany()
                        .HasForeignKey("OcorrenciaReuniaoEquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociadoSubstituto");

                    b.Navigation("AssociadoTitular");

                    b.Navigation("OcorrenciaReuniaoEquipe");
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.SubstitutoExterno", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoTitular")
                        .WithMany()
                        .HasForeignKey("AssociadoTitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", "OcorrenciaReuniaoEquipe")
                        .WithMany()
                        .HasForeignKey("OcorrenciaReuniaoEquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociadoTitular");

                    b.Navigation("OcorrenciaReuniaoEquipe");
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.VisitaInterna", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoVisitante")
                        .WithMany()
                        .HasForeignKey("AssociadoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", "OcorrenciaReuniaoEquipe")
                        .WithMany()
                        .HasForeignKey("OcorrenciaReuniaoEquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociadoVisitante");

                    b.Navigation("OcorrenciaReuniaoEquipe");
                });

            modelBuilder.Entity("AdmCC.Domain.VisitantesSubstitutos.Entities.VisitanteExterno", b =>
                {
                    b.HasOne("AdmCC.Domain.CadastroBase.Entities.Associado", "AssociadoResponsavel")
                        .WithMany()
                        .HasForeignKey("AssociadoResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", "OcorrenciaReuniaoEquipe")
                        .WithMany()
                        .HasForeignKey("OcorrenciaReuniaoEquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociadoResponsavel");

                    b.Navigation("OcorrenciaReuniaoEquipe");
                });

            modelBuilder.Entity("AdmCC.Domain.CadastroBase.Entities.Associado", b =>
                {
                    b.Navigation("AssociadosGrupamentos");

                    b.Navigation("HistoricoStatus");

                    b.Navigation("Indicados");
                });

            modelBuilder.Entity("AdmCC.Domain.CargosLiderancas.Entities.CargoLideranca", b =>
                {
                    b.Navigation("AssociadosCargos");

                    b.Navigation("Designacoes");

                    b.Navigation("EquipesCargosAtivos");
                });

            modelBuilder.Entity("AdmCC.Domain.ConexoesParcerias.Entities.ConexaoEstrategica", b =>
                {
                    b.Navigation("ValidacaoRecebimento");
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.Equipe", b =>
                {
                    b.Navigation("OcorrenciasReuniao");
                });

            modelBuilder.Entity("AdmCC.Domain.Equipes.Entities.OcorrenciaReuniaoEquipe", b =>
                {
                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.AtuacaoEspecifica", b =>
                {
                    b.Navigation("Associados");
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.Cluster", b =>
                {
                    b.Navigation("Associados");

                    b.Navigation("AtuacoesEspecificas");
                });

            modelBuilder.Entity("AdmCC.Domain.Estrategia.Entities.GrupamentoEstrategico", b =>
                {
                    b.Navigation("AssociadosGrupamentos");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.CicloSemanal", b =>
                {
                    b.Navigation("ReunioesCC");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ReuniaoCC", b =>
                {
                    b.Navigation("Validacoes");
                });

            modelBuilder.Entity("AdmCC.Domain.OperacaoSemanalReuniaoCC.Entities.ValidacaoReuniaoCC", b =>
                {
                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("AdmCC.Domain.PerfilPublico.Entities.PerfilAssociado", b =>
                {
                    b.Navigation("Midias");
                });

            modelBuilder.Entity("AdmCC.Domain.Seguro.Entities.SeguroAssociado", b =>
                {
                    b.Navigation("Beneficiarios");

                    b.Navigation("ConsentimentoLgpd");

                    b.Navigation("ContatoEmergencia");

                    b.Navigation("SolicitacoesAlteracaoBeneficiario");
                });
#pragma warning restore 612, 618
        }
    }
}
